language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install -r requirements/test.txt
script:
  - tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)
after_success:
  - coverage report
  - coveralls
notifications:
  email:
    recipients:
      - maccesch@web.de
deploy:
  provider: pypi
  user: maccesch
  password:
    secure: NoM2NEezIgizj/Q8JeezHKDDNzYsJCEBGIVJ3gAqSIhsq71hWBiA5coautBq214zIXR9P8WlX5ZzEvdEiZJc/u6jgL9Ggp2YOsi5fjGqbAdiGvlPd6lAfgnlbdNqJgjkTEckktiQEmiZYmZGz8tE57In7+BDIuxEg2QWX9eQ21E=
  on:
    tags: true
    repo: dstufft/django-passwords
